# Generated by Django 4.0.4 on 2022-05-27 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('carId', models.IntegerField()),
                ('userId', models.IntegerField(blank=True)),
                ('added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('question', models.CharField(max_length=50)),
                ('carTitle', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
