# Generated by Django 4.0.4 on 2022-06-05 17:22

import ckeditor.fields
import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(default='', max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('engine', models.SmallIntegerField()),
                ('fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Benzyna', 'Benzyna'), ('LPG', 'LPG'), ('CNG', 'CNG')], max_length=100)),
                ('transmission', models.CharField(choices=[('Manualna', 'Manualna'), ('Automatyczna', 'Automatyczna'), ('Półautomatyczna', 'Półautomatyczna')], max_length=15)),
                ('condition', models.CharField(choices=[('Nowe', 'Nowe'), ('Używane', 'Używane'), ('Uszkodzone', 'Uszkodzone')], max_length=15)),
                ('description', ckeditor.fields.RichTextField()),
                ('price', models.IntegerField()),
                ('photo1', models.ImageField(upload_to='photos/%Y%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('color', models.CharField(max_length=100)),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Interfejs Bluetooth', 'Interfejs Bluetooth'), ('Radio', 'Radio'), ('System nawigacji satelitarnej', 'System nawigacji satelitarnej'), ('Klimatyzacja automatyczna', 'Klimatyzacja automatyczna'), ('Klimatyzacja manualna', 'Klimatyzacja manualna'), ('Tapicerka skórzana', 'Tapicerka skórzana'), ('Elektrycznie ustawiany fotel kierowcy', 'Elektrycznie ustawiany fotel kierowcy'), ('Podgrzewany fotel pasażera', 'Podgrzewany fotel pasażera'), ('Podgrzewany fotel kierowcy', 'Podgrzewany fotel kierowcy'), ('Elektrycznie ustawiany fotel pasażera', 'Elektrycznie ustawiany fotel pasażera'), ('Podgrzewana przednia szyba', 'Podgrzewana przednia szyba'), ('Elektryczne szyby przednie', 'Elektryczne szyby przednie'), ('Elektryczne szyby tylne', 'Elektryczne szyby tylne'), ('Przyciemniane tylne szyby', 'Przyciemniane tylne szyby'), ('Tempomat', 'Tempomat'), ('Lampy ksenonowe', 'Lampy ksenonowe'), ('Kontrola odległości z tyłu (przy parkowaniu)', 'Kontrola odległości z tyłu (przy parkowaniu)'), ('Kamera parkowania tył', 'Kamera parkowania tył'), ('Lusterka boczne ustawiane elektrycznie', 'Lusterka boczne ustawiane elektrycznie'), ('Podgrzewane lusterka boczne', 'Podgrzewane lusterka boczne'), ('Kamera w lusterku bocznym', 'Kamera w lusterku bocznym'), ('Lampy przeciwmgielne', 'Lampy przeciwmgielne'), ('Wspomaganie kierownicy', 'Wspomaganie kierownicy'), ('ABS', 'ABS'), ('ESP', 'ESP'), ('Poduszki powietrzne', 'Poduszki powietrzne'), ('Isofix (punkty mocowania fotelika dziecięcego)', 'Isofix (punkty mocowania fotelika dziecięcego)')], max_length=800)),
                ('body', models.CharField(choices=[('Ciężarówka', 'Ciężarówka'), ('Suv', 'Suv'), ('Camper', 'Camper'), ('Mini ciężarówka', 'Mini ciężarówka'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Kombi', 'Kombi'), ('Van', 'Van'), ('Minivan', 'Minivan'), ('Roadster', 'Roadster'), ('Kabriolet', 'Kabriolet'), ('Microcar', 'Microcar'), ('Coupe', 'Coupe'), ('Pickup', 'Pickup'), ('Supersamochód', 'Supersamochód'), ('Musclecar', 'Musclecar')], max_length=100)),
                ('doors', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100)),
                ('kilometeres', models.IntegerField()),
                ('passengers', models.IntegerField()),
                ('vin', models.CharField(max_length=100)),
                ('isFeatured', models.BooleanField(default=False)),
                ('province', models.CharField(choices=[('Dolnośląskie', 'Dolnośląskie'), ('Kujawsko-Pomorskie', 'Kujawsko-Pomorskie'), ('Lubelskie', 'Lubelskie'), ('Lubuskie', 'Lubuskie'), ('Łódzkie', 'Łódzkie'), ('Małopolskie', 'Małopolskie'), ('Mazowieckie', 'Mazowieckie'), ('Opolskie', 'Opolskie'), ('Podkarpackie', 'Podkarpackie'), ('Podlaskie', 'Podlaskie'), ('Pomorskie', 'Pomorskie'), ('Śląskie', 'Śląskie'), ('Świętokrzyskie', 'Świętokrzyskie'), ('Warmińsko-mazurskie', 'Warmińsko-mazurskie'), ('Wielkopolskie', 'Wielkopolskie'), ('Zachodniopomorskie', 'Zachodniopomorskie')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
