# Generated by Django 4.0.4 on 2022-05-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_condition_alter_car_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
    ]
