# Generated by Django 4.0.4 on 2022-05-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.CharField(choices=[('Ciężarówka', 'Ciężarówka'), ('Suv', 'Suv'), ('Camper', 'Camper'), ('Mini ciężarówka', 'Mini ciężarówka'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Kombi', 'Kombi'), ('Van', 'Van'), ('Minivan', 'Minivan'), ('Roadster', 'Roadster'), ('Kabriolet', 'Kabriolet'), ('Microcar', 'Microcar'), ('Coupe', 'Coupe'), ('Pickup', 'Pickup'), ('Supersamochód', 'Supersamochód'), ('Musclecar', 'Musclecar')], max_length=100),
        ),
    ]
